[project]
name = "db-query-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.0",
    "langchain>=0.1.0",
    "langchain-ollama>=0.1.0",
    "python-dotenv>=1.0.0",
    "websocket-client>=1.6.0",
    "mem0ai>=0.1.115",
    "smolagents[helium,mcp,toolkit]>=1.20.0",
    "helium>=5.1.1",
]
